prezident aniqlash
ochiqai/python pull request #119
Opened 2023-01-08 08:29 UTC by NuriddinAI

Nima qiladi:
 - Bazada 3 ta prezident rasmi bor. Test uchun rasm kiritilsa qaysi prezidentligini qaytaradi.

Kamchilik:
- Baza rasmlari uchun maxsus papka qilib olish kerak. Gradioda faqat test rasmi kiritilishi kerak

2023-01-08 22:06 UTC, ochiqai requested changes

2023-01-15 09:47 UTC, NuriddinAI commented on projects/gradio_apps/prezident_aniqlash.py
> +    baza_embedding_1 = embedding_model.get(baza_rasm_1, kordinatalar_format[0])
Tushunarli

2023-01-21 07:00 UTC, Mukhriddinoff approved these changes
Dastur yaxshi tuzilgan

2023-01-21 08:56 UTC, orifxolbekov approved these changes
ishlatib kordim ishlayabti

2023-01-21 16:58 UTC, ochiqai approved these changes

2023-01-21 16:59 UTC, merged