Kameraga boglab
ochiqai/python pull request #125
Opened 2023-01-22 16:00 UTC by orifxolbekov

Kamera orqali gradioda ishladik

2023-01-22 16:02 UTC, orifxolbekov commented
```
Traceback (most recent call last):
  File "/home/ubuntuuser/miniconda3/envs/yuz_taqqoslash/lib/python3.9/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ubuntuuser/miniconda3/envs/yuz_taqqoslash/lib/python3.9/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/home/ubuntuuser/miniconda3/envs/yuz_taqqoslash/lib/python3.9/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/ubuntuuser/miniconda3/envs/yuz_taqqoslash/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ubuntuuser/miniconda3/envs/yuz_taqqoslash/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ubuntuuser/miniconda3/envs/yuz_taqqoslash/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/ubuntuuser/proyektlar/python/projects/gradio_apps/kameraga_boglab.py", line 38, in flip
    rasm1_embedding, rasm1_koordinatalar = embedding_olish(rasm1, yuz_aniqlagich_modul, embedding_modul)
  File "/home/ubuntuuser/proyektlar/python/projects/gradio_apps/kameraga_boglab.py", line 23, in embedding_olish
    koordinatalar = aniqlash(model_aniq, rasm)[0]
  File "/home/ubuntuuser/proyektlar/python/projects/gradio_apps/refaktor/yuzbib.py", line 107, in aniqlash
    kordinatalar, landmarklar = model.detect(rasm)
  File "/home/ubuntuuser/miniconda3/envs/yuz_taqqoslash/lib/python3.9/site-packages/insightface/model_zoo/retinaface.py", line 211, in detect
    im_ratio = float(img.shape[0]) / img.shape[1]
AttributeError: 'str' object has no attribute 'shape'

```
xatolik berdi

2023-01-23 14:06 UTC, orifxolbekov commented
tekshirib kordim ishladi

2023-01-23 16:12 UTC, NuriddinAI reviewed
Traceback (most recent call last):
  File "/home/nuriddin/miniconda3/envs/ochiqai2/lib/python3.8/site-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/home/nuriddin/miniconda3/envs/ochiqai2/lib/python3.8/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "/home/nuriddin/miniconda3/envs/ochiqai2/lib/python3.8/site-packages/gradio/blocks.py", line 856, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/nuriddin/miniconda3/envs/ochiqai2/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/nuriddin/miniconda3/envs/ochiqai2/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/nuriddin/miniconda3/envs/ochiqai2/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/nuriddin/ochiqai/python/projects/gradio_apps/kameraga_boglab.py", line 49, in kamera
    baza_rasm_kordinata = aniqlash(aniqlagich_model, baza_rasm)
  File "/home/nuriddin/ochiqai/python/projects/gradio_apps/refaktor/yuzbib.py", line 107, in aniqlash
    kordinatalar, landmarklar = model.detect(rasm)
  File "/home/nuriddin/miniconda3/envs/ochiqai2/lib/python3.8/site-packages/insightface/model_zoo/retinaface.py", line 211, in detect
    im_ratio = float(img.shape[0]) / img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

2023-01-23 16:12 UTC, NuriddinAI commented
Yuqoridagi hatolikni oldim

2023-01-23 16:14 UTC, orifxolbekov commented
bazaga ozini yukladingmi

2023-01-23 16:57 UTC, NuriddinAI commented
bazada mavjud emas deb qaytaradiku, programmani o'zini ishlatolmadim

2023-01-24 12:45 UTC, orifxolbekov commented
@NuriddinAI ishladimi

2023-01-29 16:28 UTC, ochiqai requested changes

2023-01-29 16:28 UTC, ochiqai commented on projects/gradio_apps/kameraga_boglab.py
> +#       uni kimligini qaytaradi
```suggestion
#       uni kimligini rasm balantida chap tarafda ko'rsatadi
```

2023-01-29 16:28 UTC, ochiqai commented on projects/gradio_apps/kameraga_boglab.py
> +    natija qaytariladi
```suggestion
    natija : 'numpy.ndarray'
     yuz kimga tegishligi yozilgan rasm
```

2023-01-29 16:28 UTC, ochiqai commented on projects/gradio_apps/kameraga_boglab.py
> +    rasm:'numpy.ndarray'
```suggestion
    rasm : 'numpy.ndarray'
       [b, e, c] o'lchovli matritsa. masalan [200, 400, 3]
```

2023-01-29 16:28 UTC, ochiqai commented on projects/gradio_apps/kameraga_boglab.py
> +    Kameradan rasmni olib bazadagi rasm bilan solishtiradi
```suggestion
    Kameradan rasmni olib bazadagi rasm bilan solishtiradi va ramsdagu yuz kimga tegishli
    ekanligini rasm tepasiga chap tarafga yozadi.
```

2023-01-29 16:28 UTC, ochiqai commented on projects/gradio_apps/kameraga_boglab.py
> +    embedding_modul = model_yuklash(turi="embedding")
```suggestion
    embedding_model = model_yuklash(turi="embedding")
```

2023-02-05 16:15 UTC, ochiqai reviewed
Link qo'yishimiz kerak - README.md

2023-02-05 16:44 UTC, ochiqai approved these changes
yaxshi

2023-02-05 17:03 UTC, merged