10 kun xatosi 2
ochiqai/python pull request #13
Opened 2021-12-05 15:55 UTC by Nuriddin-Dev

10-kun md file da python kodlari vertikal jihatdan to'g'irlandi.
Tekshirish:
Har bir o'zgartish tekshirish va hatolar bo'lsa ogohlantirish.

2021-12-05 16:03 UTC, ochiqai requested changes
Ok, yana ba'zi joylarda ```deb yozilib ketgan. Aslida ```python bo'lishi kerak.

2021-12-05 16:03 UTC, ochiqai commented on kunlar/10-kun-Mashqlar/10-kun.md
>      ```
python qolib ketgan. ```python bo'lishi kerak edi. Aks holda, sintaks haylayt bo'lmaydi.

2021-12-05 16:03 UTC, ochiqai commented on kunlar/10-kun-Mashqlar/10-kun.md
>      ```
python qolib ketgan. ```python bo'lishi kerak edi. Aks holda, sintaks haylayt bo'lmaydi.

2021-12-05 16:03 UTC, ochiqai commented on kunlar/10-kun-Mashqlar/10-kun.md
>      ```
python qolib ketgan. ```python bo'lishi kerak edi. Aks holda, sintaks haylayt bo'lmaydi.

2021-12-05 16:03 UTC, ochiqai commented on kunlar/10-kun-Mashqlar/10-kun.md
>      ```
python qolib ketgan. ```python bo'lishi kerak edi. Aks holda, sintaks haylayt bo'lmaydi.

2022-01-06 16:22 UTC, Nuriddin-Dev commented on kunlar/10-kun-Mashqlar/10-kun.md
>      ```
tug'irlandi. Rahmat

2022-01-17 16:50 UTC, Nuriddin-Dev commented
10-kun md fayl python kodlari qayta to'g'irlandi. Qalamcha orqali to'g'irlab chiqdim.

2022-01-22 15:31 UTC, merged