14 kun veb servis
ochiqai/python pull request #18
Opened 2021-12-29 16:16 UTC by ochiqai

**Haqida**
14-kun yozilib chiqildi. Bu veb servislar haqida.

**Qanday qilib tekshirish**
1. Tekstdagi xatolarni tekshirish
2. Kodlardagi xatolarni tekshirish

2022-01-08 12:49 UTC, Nuriddin-Dev requested changes

2022-01-08 12:49 UTC, Nuriddin-Dev commented on kunlar/14-kun-Veb-servis/14-kun-veb-servis.md
> +taqdim qilgan. Biz shunday programma tuzganmizki, uchala servisdan foydalanib bitta veb sahida hammasini
sahida - sahifada

2022-01-08 12:49 UTC, Nuriddin-Dev commented on kunlar/14-kun-Veb-servis/14-kun-veb-servis.md
> +u malumotni protsess qiladida Python list qaytaradi. Listning xar bir elementi esa dictionary bo'ladi.
Listning - Listni olganimizdan so'ng.

2022-01-08 12:49 UTC, Nuriddin-Dev commented on kunlar/14-kun-Veb-servis/14-kun-veb-servis.md
> +```
Ikkinchi dictionary dan kegin vergul bulmaydi.

2022-01-08 12:49 UTC, Nuriddin-Dev commented on kunlar/14-kun-Veb-servis/14-kun-veb-servis.md
> +- **XML**: Interda malumot almashish uchun faydalaniladigan format
faydalaniladigan - foydalaniladigan

2022-01-08 12:49 UTC, Nuriddin-Dev commented on kunlar/14-kun-Veb-servis/14-kun-veb-servis.md
> +- **JSON**: Interda malumot almashish uchun faydalaniladigan format
faydalaniladigan - foydalaniladigan

2022-01-08 12:49 UTC, Nuriddin-Dev commented on kunlar/14-kun-Veb-servis/14-kun-veb-servis.md
> +- **SOA**: Service-oriented architechture. Programmaning bazi qismlar internetdaga boshqa programmalar
`Programmaning bazi qismlar internetdaga boshqa programmalar`  shu joyi tushunarsiz.

2022-01-15 10:17 UTC, ochiqai commented on kunlar/14-kun-Veb-servis/14-kun-veb-servis.md
> +Endi, yozilishiga nazar solsak. XMLda _element_ tushunchasi mavjud. Bundga misol sifatida
To'g'irlandi rahmat.

2022-01-15 10:24 UTC, merged