03templates
ochiqai/python pull request #25
Opened 2022-06-06 12:52 UTC by Nuriddin-Dev

Templates ga oid md fayli yozib chiqildi.
Tekshirish: 
Hatolar bo'lsa aytib o'ting.
Takliflar yoki o'zgartirishlar bo'lsa izoh qoldiring.

2022-06-06 20:37 UTC, ochiqai requested changes
- [01-jangoni-urnatish](https://github.com/ochiqai/python/blob/3e1a38d8565584187f46e4f286336f68a89ff007/django/01-blog-websayt/blog-proyekt/01-djangoni-urnatish.md) o'qib chiqishni tavsiya qilaman. 
- Keyin o'sha asosida qoldirgan kommentlar ustida ishlashing kerak.

2022-06-06 20:37 UTC, ochiqai commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +```python
This is not python :)

2022-06-06 20:37 UTC, ochiqai commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +```python
Bu python emas, HTML!

2022-06-06 20:37 UTC, ochiqai commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +```python
Bu python emas

2022-06-06 20:37 UTC, ochiqai commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +```python
by python emas

2022-06-06 20:37 UTC, ochiqai commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +```python
bu python emas

2022-06-06 20:37 UTC, ochiqai commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +```python
Bu python emas.

2022-06-06 20:37 UTC, ochiqai commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +    <img src="./image/installed_app.png">
installed_app.png o'rniga kod bo'lgani yaxshi. Masalan,
```
    ```console

    ```
```

2022-06-06 20:37 UTC, ochiqai commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +    <img src="./image/head_copy.png">
head_copy.png o'rniga kod bo'lgan yaxshi, rasm yaxshi emas. Chunki, biron bir kishi qilib ko'rmoqchi bo'lsa shunchaki ko'chirib qo'yadi holos, qaytadan yozish o'rniga.

2022-06-06 20:37 UTC, ochiqai commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +    <img src="./image/body_js.png">
body_js.png o'rniga kod bo'lgan yaxshi, rasm yaxshi emas. Chunki, biron bir kishi qilib ko'rmoqchi bo'lsa shunchaki ko'chirib qo'yadi holos, qaytadan yozish o'rniga.

2022-06-06 20:37 UTC, ochiqai commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +    <img src="./image/body_copy.png">
body_copy.png o'rniga kod bo'lgan yaxshi, rasm yaxshi emas. Chunki, biron bir kishi qilib ko'rmoqchi bo'lsa shunchaki ko'chirib qo'yadi holos, qaytadan yozish o'rniga.

2022-06-06 20:37 UTC, ochiqai commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +* Terminalga borib serverni ishlatib ko'ramiz.
qanday yana kommandani qo'yganimiz yaxshi?

2022-06-08 11:45 UTC, Nuriddin-Dev commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +    <img src="./image/installed_app.png">
Tushundim, rahmat

2022-06-08 12:00 UTC, Nuriddin-Dev commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +```python
Thanks

2022-06-08 12:01 UTC, Nuriddin-Dev commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +    <img src="./image/head_copy.png">
_Tushunarli, Rahmat_

2022-06-08 12:10 UTC, Nuriddin-Dev commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +    <img src="./image/body_js.png">
_Tushunarli, rahmat_

2022-06-08 12:10 UTC, Nuriddin-Dev commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +    <img src="./image/body_copy.png">
_Tushunarli, rahmat_

2022-06-08 12:40 UTC, Nuriddin-Dev commented on django/01-blog-websayt/blog-proyekt/03-templates.md
> +* Terminalga borib serverni ishlatib ko'ramiz.
`python manage.py runserver`

2022-06-11 21:19 UTC, ochiqai approved these changes
Yaxshi, yozish ancha rivojlangan!

2022-06-11 21:19 UTC, merged