README.md faylga bir qanch qo'shimchalar qo'shildi.
ochiqai/python pull request #55
Opened 2022-11-07 18:15 UTC by Mukhriddinoff

README.md faylga Proyektlar qismi qo'shildi. Ularni tahlil qilish

2022-11-08 05:42 UTC, Nuriddin-Dev approved these changes
yaxshi

2022-11-08 07:00 UTC, orifxolbekov commented
@Mukhriddinoff salom bunda orinlarini bir qarab chiqishni maslahat berardim vektorlarni solishtirmasdan yuzlarni solishtirish sal murakkabroq

2022-11-08 22:25 UTC, ochiqai requested changes
Yaxshi, yuzlarni solishtirish biznini bosh proyektimiz. Qolganlari kerakli narsalar erishishimiz uchun.

2022-11-08 22:25 UTC, ochiqai commented on README.md
Quyidagicha o'zgartirishni maslahat beraman: 

 1. Yuzlarni solishtirish
     1.0 [Condani o'rnatish](yozilayapti)
     1.1 [Conda orqali muhit yaratish](yozilyapti)
     1.2 [Kutubxonalarni o'rnatish](yozilyapti)
     1.3 [Kerakli kutubxonalarda ishlash](yozilyapti)
     1.4 [NumPy da ishlash](yozilyapti)
     1.5 [Matplotlibda da ishlash](yozilayapti)
     1.6 [Vektorlarni solishtirish](yozilyapti)
     1.7 [Yuzlarni rasmdan aniqlash](yozilayapti)
     1.8 [Yuzlarni piksellar orqali solishtirish](yozilyapti)
     1.9 [Yuzlarni AI orqali vektorlarga o'tkazish va solishtirish](yozilyapti)

2022-11-08 22:25 UTC, ochiqai commented
@Nuriddin-Dev @orifxolbekov @Mukhriddinoff Biz imlo xatolarga ham e'tibo berishimiz kerak.

2022-11-10 21:32 UTC, Mukhriddinoff commented on README.md
o'zgarish kiritildi

2022-11-10 21:58 UTC, Mukhriddinoff commented on README.md
tartibi boshqa bo'ldi. yani:
1. Condani o'rnatish
2 Conda orqali muhit yaratish
3. Kutubxonalarni o'rnatish
4. Kerakli kutubxonalarda ishlash
5. NumPy da ishlash
6. Matplotlibda da ishlash

shu tartibda joylashtirdim 

1.0
1.1
 bu tartibda ketma - ketlikka tushmayapti

2022-11-10 23:15 UTC, ochiqai commented on README.md
>shu tartibda joylashtirdim

Tepada ko'rsatdimku qanday qilish

2022-11-11 19:57 UTC, orifxolbekov approved these changes

2022-11-12 16:53 UTC, Mukhriddinoff commented on README.md
Yozildi tartib bo'yicha

2022-11-12 17:37 UTC, ochiqai approved these changes
yaxshi.

2022-11-12 17:37 UTC, merged