Conda muhit
ochiqai/python pull request #57
Opened 2022-11-11 10:14 UTC by orifxolbekov

yangi conda muhit yaratish uchun PR ochildi

2022-11-11 13:35 UTC, Mukhriddinoff commented
Imloviy xatolar mavjud, keyin MD kam bölib qolganday

2022-11-11 19:49 UTC, orifxolbekov commented
kam boldi kimda taklif bolsa beringlar men conda ornatish muhit yaratish larni bitta qilgandim aloxida qilish kkmi keyin rasmlarni togri berganmanmi korinayabtimi sizlargayam

2022-11-12 13:15 UTC, Mukhriddinoff reviewed
Mddagi yozuvlar tartibini ham to'g'irlash kerak, keyin rasmlar ham yozuvlarga qo'shilib ketgan, ajratib chiqish kerak

2022-11-12 17:34 UTC, ochiqai requested changes
Boshlanishi yaxshi.
Quyidagilar o'zgartirishlarni qilishimiz kerak. 

1. .idea degan papkani push qilmasligimiz kerak, U har bar pycharm foyrdalanuvchida alohida bo'ladi. To'g'irlash: buni biz .gitignore fayliga qushib quyamiz. 
2. Qaytadan yozgan bo'lardim. 
 Muhit yaratish uchun quyidagi qadamlardan iborat:
> 1. `environment.yml` nomli fayl yaratamiz
> 2. Ichida kerakli kutubxonalarni yozamiz  
> 3. `conda env create -f environment.yml`
> 4. Aktivatsiya qilamiz:
>    - `conda activate nomi`
> 5. Deaktivatsiya qilish uchun
>    - `conda deactivate nomi`
3. Rasmlarni kerakli joyini olib quyishimiz kerak,
4. Fayl strukturasi o'zgartirilish kerak. Oson navigatsiya uchun. 
![image](https://user-images.githubusercontent.com/89749192/201487030-409e6fcb-4afb-42de-ae64-b7ba034461b4.png)

2022-11-12 17:40 UTC, ochiqai reviewed
orif papaksini o'chiramiz.

2022-11-13 14:49 UTC, Nuriddin-Dev commented on conda_muhit.md
> +Biz projectlar bilan ishlayotganimizda kutibxonalarga murojat qilamiz,har xil projektda ishlaganimizda turlixil biblatrkalar
turlixil biblatrkalar - turli xil biblatekalar

2022-11-13 14:50 UTC, Nuriddin-Dev commented on conda_muhit.md
> + ornatganimizda bizda ba'zi muammolar kelib chiqishi mumkin, masalan `Django` da bizga ishlatiladigan kutibxonalar
ornatganimizda - o'rnatganimizda

2022-11-13 14:51 UTC, Nuriddin-Dev commented on conda_muhit.md
> +`AI` da ishlatilmasligi mumkin shuning uchin biz ozimizga qulay bolgan muhit (`environment`) yaratib olish maqsasdga muvofiq boladi
bolgan - bo'lgan

2022-11-13 14:51 UTC, Nuriddin-Dev commented on conda_muhit.md
> +`AI` da ishlatilmasligi mumkin shuning uchin biz ozimizga qulay bolgan muhit (`environment`) yaratib olish maqsasdga muvofiq boladi
maqsasdga  - maqsadga

2022-11-13 14:52 UTC, Nuriddin-Dev commented on conda_muhit.md
> +Muhit yaratish uchun `Minnicondadan` foydalanamiz.birinchi orinda kompyuterga Minni kondani o'rnatib olamiz
.birinchi  - nuqtadan so'ng bosh harf bilan joy tashlab yozish kerak

2022-11-13 14:56 UTC, Nuriddin-Dev requested changes
1. Imloviy hatolar mavjud.
2. Rasm o'lchamlari va kerakli qismini quyish.
3. Terminal buyruqlarini alohida ko'rsatib o'tish.
Masalan :
      ```python
      shunaqa ko'rinishda
      ```

2022-11-19 16:55 UTC, closed without merging