condani-urnatish
ochiqai/python pull request #71
Opened 2022-11-14 21:20 UTC by orifxolbekov

2022-11-14 21:33 UTC, ochiqai requested changes
Boshlanishi yaxshi, kommentlar tashladim. O'shlar ustida ishlang.

2022-11-14 21:33 UTC, ochiqai commented on projects/condani_o'rnatish.md
> + -  ![img.png](rasmlar_1/img.png)
Bu yerda `rasmlar_1` papka yo'q. `rasmlar` papkasi ochilsinda uning ichiga rasm qo'yilsin, img.png nomi ham manodor nomga o'zgartirilsin.

2022-11-14 21:33 UTC, ochiqai commented on projects/condani_o'rnatish.md
> +2. `bash Miniconda3-latest-Linux-x86_64.sh` terminalda kiritamiz
Yuq etapini ha aytish kerak, Bazi joylarda yes deydigan narsalara chiqadi ushani rasmlarini ham quysak yaxshi bo'ladi.

2022-11-14 21:33 UTC, ochiqai commented on projects/condani_o'rnatish.md
> +3. `conda` deb tekshirib koramiz
nima chiqasa ishlagan bo'ladi. Rasmini qo'ysak yokli kodini  tashlasak yaxshi bo'ladi.

2022-11-15 12:40 UTC, Mukhriddinoff reviewed
pull request oxiriga yetmaganmi

2022-11-19 16:54 UTC, closed without merging