Vektorlarni taqqoslash
ochiqai/python pull request #74
Opened 2022-11-15 10:22 UTC by Nuriddin-Dev

Tekshirish:
Hatolar bulsa aytib utish.
Uzgartirilishi kerak bulgan joylarga taklif bildirish.
Kerakmas qismi bulsa yoki kamchilik , izoh qoldirish.

2022-11-15 12:53 UTC, Mukhriddinoff approved these changes
Zooor, ancha tushunarli yozilibdi

2022-11-15 12:53 UTC, Mukhriddinoff commented on projects/vektorlarni_taqqoslash.md
> +### Pytohnda vektorlar haqida tushuncha va ularning taqqoslanishi.
Pythonda qilib yuboring

2022-11-15 23:44 UTC, ochiqai requested changes
Ajoyib ancha yaxshi bo'lgan. bir nechta kommentlar qoldirdim. Keyin boshqa taskka etibor qilsangiz bo'laveradi.

2022-11-15 23:44 UTC, ochiqai commented on projects/vektorlarni_taqqoslash.md
> +Oddiy so'z bilan aytganda vektorni bir o'lchovli massiv deb hisoblash mumkin. Python tiliga kelsak, vektor ro'yxatlarning bir o'lchovli massividir. U elementlarni Python ro'yxatiga o'xshash tarzda eg
massiv nima?

2022-11-15 23:44 UTC, ochiqai commented on projects/vektorlarni_taqqoslash.md
> +Python NumPy moduli vektor yaratish uchun ishlatiladi. Bir o'lchovli massiv, ya'ni vektor yaratish uchun numpy.array() usulidan foydalanamiz.
Python degan kerakmas. O'zi Pythonda ishlayapmiz.

2022-11-15 23:44 UTC, ochiqai commented on projects/vektorlarni_taqqoslash.md
> +Python NumPy moduli vektor yaratish uchun ishlatiladi. Bir o'lchovli massiv, ya'ni vektor yaratish uchun numpy.array() usulidan foydalanamiz.
usul emas, metodidan yoki funksiyasidan.

2022-11-15 23:44 UTC, ochiqai commented on projects/vektorlarni_taqqoslash.md
> +import numpy as np
har doim `import numpy as np` deb yozishimiz shart emas. Bir marta yetadi.

2022-11-15 23:44 UTC, ochiqai commented on projects/vektorlarni_taqqoslash.md
> +lst = [10,20,30,40,50]
sonlar orasiga ` ` bo'shliq qo'yish kerak.

2022-11-15 23:44 UTC, ochiqai commented on projects/vektorlarni_taqqoslash.md
> +Bunda ikki vektorning elementlari buyicha amal bajariladi va ikkala vektorning ham uzunligi bir xil buladi.
buyicha >> bo'yicha
boshqalari ham tekshirilib chiqilsin

2022-11-15 23:44 UTC, ochiqai commented on projects/vektorlarni_taqqoslash.md
> +vctr_add = vctr1+vctr2
`vctr1+vctr2` >> `vctr1 + vctr2`

2022-11-15 23:44 UTC, ochiqai commented on projects/vektorlarni_taqqoslash.md
> +vctr_add = vctr1+vctr2
boshqa hoylar ham shunday qilinsing

2022-11-19 05:10 UTC, Nuriddin-Dev commented on projects/vektorlarni_taqqoslash.md
> +vctr_add = vctr1+vctr2
tushunarli

2022-11-19 05:11 UTC, Nuriddin-Dev commented on projects/vektorlarni_taqqoslash.md
> +#### Vektor Dot
bu qo'shimcha, shunaqa metodi ham bor ekan

2022-11-19 05:12 UTC, Nuriddin-Dev commented on projects/vektorlarni_taqqoslash.md
> +import numpy as np
Bior kishi nusxa olib ishlatib ko'rishi mumkin

2022-11-19 05:28 UTC, Nuriddin-Dev commented on projects/vektorlarni_taqqoslash.md
> +Oddiy so'z bilan aytganda vektorni bir o'lchovli massiv deb hisoblash mumkin. Python tiliga kelsak, vektor ro'yxatlarning bir o'lchovli massividir. U elementlarni Python ro'yxatiga o'xshash tarzda eg
Dasturlash tillarida ro’yxat yoki jadval ko’rinishidagi ma’lumotlarni massiv deb atashadi. Massiv so’zining ma’nosi o’lcham, o’lchov demakdir. Massivning barcha elementlari bitta turga mansub bo’lib, ular bitta nom bilan nomlanadi va bir-birlaridan nomerlari (indekslari) bilan farq qiladi.

2022-11-19 06:00 UTC, Nuriddin-Dev commented on projects/vektorlarni_taqqoslash.md
> +### Pytohnda vektorlar haqida tushuncha va ularning taqqoslanishi.
Mundarija quydim lekin, link ustiga bossam ishlamayabdi?

2022-11-19 06:03 UTC, Nuriddin-Dev commented
Hatolar tug'irlandi

2022-11-19 17:23 UTC, ochiqai approved these changes
Yaxshi

2022-11-19 17:23 UTC, merged