flameshot install
ochiqai/python pull request #86
Opened 2022-11-20 18:59 UTC by Nuriddin-Dev

**Flameshotni qanday o'rnatish haqida md fayl yozildi.**

- Tekshirish:
    - Hato yoki kamchilik bo'lsa taklif bildirish

2022-11-20 19:26 UTC, Nuriddin-Dev commented
Ko'rib chiqdim

2022-11-20 22:03 UTC, ochiqai requested changes
Flameshotdan foydalanishimiz kerak bu PR da.

2022-11-20 22:03 UTC, ochiqai commented on Maslahatlar/flameshot-install.md
> +    <img src="./rasmlar/flameshot_terminal_comandasi.png" width="650">
buni terminal ko'rinishda yozishimiz kerak. Masalan

```'shell
a@b: sudo snap install flameshot
...
```

2022-11-20 22:03 UTC, ochiqai commented on Maslahatlar/flameshot-install.md
> +    <img src="./rasmlar/frameshot.png" width="650">
Qo'shimcha: so'zda yozganingizni, falemshotda turburchakka olib, belgi qilib ko'rsating. shunda o'quvchi qayerga qarash kerakligini tezda biladi.

2022-11-23 15:32 UTC, Nuriddin-Dev commented on Maslahatlar/flameshot-install.md
> +    <img src="./rasmlar/frameshot.png" width="650">
ok

2022-11-27 16:54 UTC, ochiqai commented on Maslahatlar/flameshot-install.md
> +</p>
programmani qanday o'chirib tashlashlikni qo'shishimiz kerak.

2022-12-02 16:13 UTC, Elyorcv approved these changes
yaxshi

2022-12-02 16:21 UTC, ochiqai approved these changes
yaxshi

2022-12-02 16:21 UTC, merged