conda urnatishga uzgartirishlar kiritildi
ochiqai/python pull request #89
Opened 2022-12-03 07:59 UTC by NuriddinAI

**Conda O'rnatishga o'zgarishlar kiritildi.**
_Tekshirish:_
    -  _Kamchilik yoki hatolar bo'lsa aytish_

2022-12-10 00:00 UTC, ochiqai requested changes
Birinchi o'zing review qilib chiqgin. Rasmlardan markdownda qila olmasakgina foydalanaylik

2022-12-10 00:48 UTC, ochiqai commented on projects/yuzlarni-taqqoslash/doklar/1-0-conda-urnatish.md
> +1. `https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html` linkdan foydalanib yukalb olamiz.
qayerga yuklab olamiz, joyi ko'rsatilsa aniqroq bo'ladi.

2022-12-10 11:44 UTC, Mukhriddinoff approved these changes
yaxshi yozilgan

2022-12-11 11:47 UTC, orifxolbekov approved these changes
korib chiqdim

2022-12-15 18:04 UTC, NuriddinAI reviewed
Tekshirildi.

2022-12-15 18:10 UTC, NuriddinAI commented on projects/yuzlarni-taqqoslash/doklar/1-0-conda-urnatish.md
> +1. `https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html` linkdan foydalanib yukalb olamiz.
`Terminalga kiramiz va condani yuklab olgan qismiga boramiz(papkasi)`.  Aytib o'tilgan.

2022-12-15 20:47 UTC, ochiqai approved these changes

2022-12-15 20:47 UTC, merged