muhit yaratishga qo'shimchalar kiritildi
ochiqai/python pull request #90
Opened 2022-12-03 11:29 UTC by NuriddinAI

O'zgarishlar kiritildi. Hato ypki taklif bulsa ayting

2022-12-09 23:57 UTC, ochiqai requested changes
Birinchi o'zing review qilib chiqgin

2022-12-10 11:42 UTC, Mukhriddinoff approved these changes
Yaxshi yozilgan

2022-12-11 11:49 UTC, orifxolbekov approved these changes

2022-12-15 17:58 UTC, NuriddinAI reviewed
O'zim tekshirdim

2022-12-15 20:47 UTC, ochiqai approved these changes

2022-12-15 20:47 UTC, merged